// <auto-generated />
using System;
using LogiTrack.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogiTrack.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241030171559_InitialMigrationToNewDatabase")]
    partial class InitialMigrationToNewDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlternativePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Company's alternative phone number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Company's city");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Person whom we are contacting");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Company's country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Registration created at");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company's industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company Name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComment("Company's postal code");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasComment("Company's registration number");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company's registration status");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company's address");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("ClientCompanies");

                    b.HasComment("Client Company Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlternativePhoneNumber = "1234567891",
                            City = "Sliven",
                            ContactPerson = "John Doe",
                            Country = "Bulgaria",
                            CreatedAt = new DateTime(2024, 10, 10, 19, 15, 56, 528, DateTimeKind.Local).AddTicks(4805),
                            Industry = "Manufacturing",
                            Name = "Client Company 1",
                            PostalCode = "8800",
                            RegistrationNumber = "REG123456",
                            RegistrationStatus = "Approved",
                            Street = "Sini kamani 28",
                            UserId = "20450cff-816f-49c8-9546-1c603aec0301"
                        },
                        new
                        {
                            Id = 2,
                            AlternativePhoneNumber = "9876543210",
                            City = "Sofia",
                            ContactPerson = "Jane Smith",
                            Country = "Bulgaria",
                            CreatedAt = new DateTime(2024, 10, 20, 19, 15, 56, 528, DateTimeKind.Local).AddTicks(4830),
                            Industry = "Fashion",
                            Name = "Client Company 2",
                            PostalCode = "1000",
                            RegistrationNumber = "REG654321",
                            RegistrationStatus = "Pending",
                            Street = "Osogovo 5a"
                        });
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasComment("Invoice identifier");

                    b.Property<int?>("ClientCompanyId1")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Invoice description");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("File identifier in Google drive");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasComment("Invoice date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Invoice number");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasComment("Is invoice paid");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId1");

                    b.ToTable("Invoices");

                    b.HasComment("Invoice Entity");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Offer identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClientCompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Company identifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Notes for the offer");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("datetime2")
                        .HasComment("Offer date");

                    b.Property<string>("OfferStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Offer status");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasComment("Request identifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("IX_Offer_DeliveryId");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_Offer_RequestId");

                    b.ToTable("Offers");

                    b.HasComment("Offer Entity");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Request identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ApproximatePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Approximate price given by the company");

                    b.Property<decimal>("CalculatedPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Automatically calculated price");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Cargo type");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("int")
                        .HasComment("Client Company identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Date of creation");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Delivery address");

                    b.Property<double>("DeliveryLatitude")
                        .HasColumnType("float")
                        .HasComment("Delivery address latitude");

                    b.Property<double>("DeliveryLongitude")
                        .HasColumnType("float")
                        .HasComment("Delivery address longitude");

                    b.Property<DateTime>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2")
                        .HasComment("Expected delivery date");

                    b.Property<bool>("IsRefrigerated")
                        .HasColumnType("bit")
                        .HasComment("Is the cargo refrigerated");

                    b.Property<double>("Kilometers")
                        .HasColumnType("float");

                    b.Property<int?>("NumberOfNonStandartGoods")
                        .HasColumnType("int")
                        .HasComment("Number of non-standart goods");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int")
                        .HasComment("Offer identifier");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Pickup address");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("float")
                        .HasComment("Pickup address latitude");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("float")
                        .HasComment("Pickup address longitude");

                    b.Property<bool>("SharedTruck")
                        .HasColumnType("bit")
                        .HasComment("Will the vehicle be shared or no");

                    b.Property<string>("SpecialInstructions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Special instructions");

                    b.Property<int>("StandartCargoId")
                        .HasColumnType("int")
                        .HasComment("Standart cargo identifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Status of the request");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("float");

                    b.Property<double>("TotalWeight")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Type of the request");

                    b.Property<string>("TypeOfGoods")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Type of goods");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("Requests");

                    b.HasComment("Request Entity");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Vehicle identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ArePalletsStackable")
                        .HasColumnType("bit")
                        .HasComment("Are the pallets stackable");

                    b.Property<decimal>("ContantsExpenses")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Vehicle's constant expences");

                    b.Property<int>("EuroPalletCapacity")
                        .HasColumnType("int")
                        .HasComment("Euro pallets capacity");

                    b.Property<double>("FuelConsumptionPer100Km")
                        .HasColumnType("float")
                        .HasComment("Fuel consumption per 100 km");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasComment("Vehicle height");

                    b.Property<int>("IndustrialPalletCapacity")
                        .HasColumnType("int")
                        .HasComment("Industrial pallets capacity");

                    b.Property<double>("KilometersDriven")
                        .HasColumnType("float")
                        .HasComment("Kilometers driven");

                    b.Property<double>("KilometersLeftToChangeParts")
                        .HasColumnType("float")
                        .HasComment("Kilometers left to change parts");

                    b.Property<DateTime>("LastYearMaintenance")
                        .HasColumnType("datetime2")
                        .HasComment("Maintenance due date");

                    b.Property<double>("Length")
                        .HasColumnType("float")
                        .HasComment("Vehicle length");

                    b.Property<double>("MaxWeightCapacity")
                        .HasColumnType("float")
                        .HasComment("Max weight capacity");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Vehicle's purchase price");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasComment("Vehicle registration number");

                    b.Property<string>("VehicleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Vehicle status");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Vehicle type");

                    b.Property<double>("Volume")
                        .HasColumnType("float")
                        .HasComment("Vehicle volume");

                    b.Property<double>("Width")
                        .HasColumnType("float")
                        .HasComment("Vehicle width");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasComment("Vehicle Entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Calendar Event identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("int")
                        .HasComment("Client Company identifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Event Type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Title");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("CalendarEvents");

                    b.HasComment("Calendar Event Entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Cash Register identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Amount of the register");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2")
                        .HasComment("Date submitted");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Description of the register");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("File identifier in Google drive");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Type of the register");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.ToTable("CashRegisters");

                    b.HasComment("Cash Register Entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryStep")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasComment("Driver identifier");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasComment("Invoice identifier");

                    b.Property<int>("OfferId")
                        .HasColumnType("int")
                        .HasComment("Offer identifier");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Delivery total income");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Delivery reference number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Delivery status");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Delivery total expenses");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasComment("Vehicle identifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("IX_Delivery_DriverId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_Delivery_VehicleId");

                    b.ToTable("Deliveries");

                    b.HasComment("Delivery Entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.DeliveryTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasComment("Driver identifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasComment("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasComment("Longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Notes");

                    b.Property<string>("StatusUpdate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Status update");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasComment("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("DriverId");

                    b.ToTable("DeliveryTrackings");

                    b.HasComment("Delivery Tracking Entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Driver identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Driver's age");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasComment("Is driver available");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2")
                        .HasComment("Driver's license expiry date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Driver's license number");

                    b.Property<int>("MonthsOfExperience")
                        .HasColumnType("int")
                        .HasComment("Driver's months of experience");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Driver's name");

                    b.Property<string>("Preferrences")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Driver's preferrences");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Driver's salary");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int")
                        .HasComment("Driver's year of experience");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drivers");

                    b.HasComment("Driver Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            IsAvailable = false,
                            LicenseExpiryDate = new DateTime(2026, 10, 30, 17, 15, 56, 537, DateTimeKind.Utc).AddTicks(3092),
                            LicenseNumber = "DL123456",
                            MonthsOfExperience = 6,
                            Name = "Paul Smith",
                            Preferrences = "Long-distance deliveries",
                            Salary = 3000m,
                            UserId = "f3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b",
                            YearOfExperience = 10
                        });
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.FuelPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Fuel Price identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Date");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Fuel price");

                    b.HasKey("Id");

                    b.ToTable("FuelPrices");

                    b.HasComment("Fuel Prices Entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.NonStandardCargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Non-standard cargo identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Description of the non-standard cargo");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasComment("Height of the goods");

                    b.Property<double>("Length")
                        .HasColumnType("float")
                        .HasComment("Length of the goods");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasComment("Request identifier");

                    b.Property<double>("Volume")
                        .HasColumnType("float")
                        .HasComment("Volume of the goods");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasComment("Weight of the goods");

                    b.Property<double>("Width")
                        .HasColumnType("float")
                        .HasComment("Width of the goods");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("NonStandardCargos");

                    b.HasComment("Non-Standard Cargo Entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.PricesPerSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Prices per size identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("DomesticPriceForNotSharedTruck")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Domestic price for shared truck");

                    b.Property<decimal>("DomesticPriceForSharedTruck")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Domestic price for shared truck");

                    b.Property<decimal>("InternationalPriceForNotSharedTruck")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("International price for shared truck");

                    b.Property<decimal>("InternationalPriceForSharedTruck")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("International price for shared truck");

                    b.Property<double>("QuotientForDomesticNotSharedTruck")
                        .HasColumnType("float")
                        .HasComment("Quotient for domestic not shared truck");

                    b.Property<double>("QuotientForDomesticSharedTruck")
                        .HasColumnType("float")
                        .HasComment("Quotient for domestic shared truck");

                    b.Property<double>("QuotientForInternationalNotSharedTruck")
                        .HasColumnType("float")
                        .HasComment("Quotient for international not shared truck");

                    b.Property<double>("QuotientForInternationalSharedTruck")
                        .HasColumnType("float")
                        .HasComment("Quotient for international shared truck");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasComment("Vehicle identifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("PricesPerSize");

                    b.HasComment("Prices per size entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.StandartCargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Standard cargo identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("NumberOfPallets")
                        .HasColumnType("int")
                        .HasComment("Number of pallets");

                    b.Property<double?>("PalletHeight")
                        .HasColumnType("float")
                        .HasComment("Pallet height");

                    b.Property<double?>("PalletLength")
                        .HasColumnType("float")
                        .HasComment("Pallet length");

                    b.Property<double?>("PalletVolume")
                        .HasColumnType("float")
                        .HasComment("Pallet volume");

                    b.Property<double?>("PalletWidth")
                        .HasColumnType("float")
                        .HasComment("Pallet width");

                    b.Property<bool?>("PalletsAreStackable")
                        .HasColumnType("bit")
                        .HasComment("Are the pallets stackable");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasComment("Request identifier");

                    b.Property<string>("TypeOfPallet")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Type of pallet");

                    b.Property<double?>("WeightOfPallets")
                        .HasColumnType("float")
                        .HasComment("Weight of pallets");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("StandartCargos");

                    b.HasComment("Standart Cargo Entity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99027aaa-d346-4dd9-a467-15d74576c080",
                            ConcurrencyStamp = "84bb71f9-940f-4e07-942c-6acb07993016",
                            Name = "LogisticsCompany",
                            NormalizedName = "LOGISTICSCOMPANY"
                        },
                        new
                        {
                            Id = "5d000e64-c056-419a-950f-1992bd1e910d",
                            ConcurrencyStamp = "1489fcaa-9685-4da4-babf-fead30ff1b1e",
                            Name = "ClientCompany",
                            NormalizedName = "CLIENTCOMPANY"
                        },
                        new
                        {
                            Id = "20ddc22c-ca6d-4feb-a688-0f31a430b5eb",
                            ConcurrencyStamp = "82dc2d15-ff7c-47c4-93ca-7dec6ad75598",
                            Name = "Accountant",
                            NormalizedName = "ACCOUNTANT"
                        },
                        new
                        {
                            Id = "27609f35-fbc8-4dc4-9d12-7ff2dd400327",
                            ConcurrencyStamp = "32abf858-9498-4595-b660-ad721d775b2f",
                            Name = "Speditor",
                            NormalizedName = "SPEDITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6bab54d5-5a88-4128-92d2-4d12ad0baa32",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "446feff0-673c-4a2d-bfe5-b8242e947006",
                            Email = "logistics@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEMa01FR5ZksVwWf0UuxqzW+pWT5Lpx95FONQmMVWominO8r9cDQVwKmsWQh2gayGSA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1a3d398-eb40-4787-93b0-a0edf75fef97",
                            TwoFactorEnabled = false,
                            UserName = "logistics"
                        },
                        new
                        {
                            Id = "20450cff-816f-49c8-9546-1c603aec0301",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8087c70d-5dcb-471e-a35a-161ef31cfc0a",
                            Email = "clientcompany1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEDMKBIP0yBoCZruZD6dkucaXGh1fvz+hG4rCgvvOSCWG1ZkKe58eeNHExgvzd7bbdw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e232110f-29bd-4a30-b0b8-9b90e1627530",
                            TwoFactorEnabled = false,
                            UserName = "clientcompany1"
                        },
                        new
                        {
                            Id = "38ba6810-2800-4ac8-b005-5c27e8248951",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1c671f2-735f-4d2f-884e-67da5bf5ca06",
                            Email = "secretary@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEGeASuXE2sMD5wXy51f6LZEAGJsmnAKfPl8kUAm0PMqeX3SBNBWv5YInLyr8/1SxoA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "50bd3e0d-8b3d-4754-b126-149b0b405ea3",
                            TwoFactorEnabled = false,
                            UserName = "secretary"
                        },
                        new
                        {
                            Id = "2e8be95a-186e-403b-b4aa-3874750a3563",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e38c56e-edd1-43d6-8c93-c78d67d9b5f5",
                            Email = "speditor@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEAIw+iQxurK/8zyvnQf9OC9nEJdl1vZWP5BAXfnv5hp6Nv9XGrd47df4DpGbHPvaAQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fc8fd112-d48a-467d-82a8-0e9a682e52f8",
                            TwoFactorEnabled = false,
                            UserName = "speditor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "6bab54d5-5a88-4128-92d2-4d12ad0baa32",
                            RoleId = "99027aaa-d346-4dd9-a467-15d74576c080"
                        },
                        new
                        {
                            UserId = "20450cff-816f-49c8-9546-1c603aec0301",
                            RoleId = "5d000e64-c056-419a-950f-1992bd1e910d"
                        },
                        new
                        {
                            UserId = "38ba6810-2800-4ac8-b005-5c27e8248951",
                            RoleId = "20ddc22c-ca6d-4feb-a688-0f31a430b5eb"
                        },
                        new
                        {
                            UserId = "2e8be95a-186e-403b-b4aa-3874750a3563",
                            RoleId = "27609f35-fbc8-4dc4-9d12-7ff2dd400327"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Invoice", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", null)
                        .WithMany("Invoices")
                        .HasForeignKey("ClientCompanyId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Delivery", "Delivery")
                        .WithOne("Invoice")
                        .HasForeignKey("LogisticsSystem.Infrastructure.Data.DataModels.Invoice", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Offer", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", null)
                        .WithMany("Offers")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Request", "Request")
                        .WithOne("Offer")
                        .HasForeignKey("LogisticsSystem.Infrastructure.Data.DataModels.Offer", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Request", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", "ClientCompany")
                        .WithMany("Requests")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.CalendarEvent", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", "ClientCompany")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.CashRegister", b =>
                {
                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Delivery", "Delivery")
                        .WithMany("CashRegisters")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Delivery", b =>
                {
                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Driver", "Driver")
                        .WithMany("Deliveries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Offer", "Offer")
                        .WithOne("Delivery")
                        .HasForeignKey("LogiTrack.Infrastructure.Data.DataModels.Delivery", "OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Vehicle", "Vehicle")
                        .WithMany("Deliveries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Offer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.DeliveryTracking", b =>
                {
                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Delivery", "Delivery")
                        .WithMany("DeliveryTrackings")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Driver", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("LogiTrack.Infrastructure.Data.DataModels.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.NonStandardCargo", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Request", "Request")
                        .WithMany("NonStandardCargos")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.PricesPerSize", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Vehicle", "Vehicle")
                        .WithOne()
                        .HasForeignKey("LogiTrack.Infrastructure.Data.DataModels.PricesPerSize", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.StandartCargo", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Request", "Request")
                        .WithOne("StandartCargo")
                        .HasForeignKey("LogiTrack.Infrastructure.Data.DataModels.StandartCargo", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("Invoices");

                    b.Navigation("Offers");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Offer", b =>
                {
                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Request", b =>
                {
                    b.Navigation("NonStandardCargos");

                    b.Navigation("Offer");

                    b.Navigation("StandartCargo");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Vehicle", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Delivery", b =>
                {
                    b.Navigation("CashRegisters");

                    b.Navigation("DeliveryTrackings");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Driver", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
