// <auto-generated />
using System;
using LogiTrack.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogiTrack.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlternativePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Company's alternative phone number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Company's city");

                    b.Property<string>("CompanySize")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company's size");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Person whom we are contacting");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Company's country");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company's industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company Name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComment("Company's postal code");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasComment("Company's registration number");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company's registration status");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company's address");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasComment("Company's vat number");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("ClientCompanies");

                    b.HasComment("Client Company Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlternativePhoneNumber = "1234567891",
                            City = "Sliven",
                            CompanySize = "Medium",
                            ContactPerson = "John Doe",
                            Country = "Bulgaria",
                            Industry = "Manufacturing",
                            Name = "Client Company 1",
                            PostalCode = "8800",
                            RegistrationNumber = "REG123456",
                            RegistrationStatus = "Approved",
                            Street = "Sini kamani 28",
                            UserId = "20450cff-816f-49c8-9546-1c603aec0301",
                            VatNumber = "VAT123456"
                        },
                        new
                        {
                            Id = 2,
                            AlternativePhoneNumber = "9876543210",
                            City = "Sofia",
                            CompanySize = "Large",
                            ContactPerson = "Jane Smith",
                            Country = "Bulgaria",
                            Industry = "Fashion",
                            Name = "Client Company 2",
                            PostalCode = "1000",
                            RegistrationNumber = "REG654321",
                            RegistrationStatus = "Rejected",
                            Street = "Osogovo 5a",
                            VatNumber = "VAT654321"
                        });
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasComment("Invoice identifier");

                    b.Property<int?>("ClientCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasComment("Invoice date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Invoice number");

                    b.Property<int>("OfferId")
                        .HasColumnType("int")
                        .HasComment("Offer identifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("Invoices");

                    b.HasComment("Invoice Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InvoiceDate = new DateTime(2024, 10, 19, 1, 10, 32, 348, DateTimeKind.Utc).AddTicks(6835),
                            InvoiceNumber = "INV-2024-0001",
                            OfferId = 1
                        });
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Offer identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClientCompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Company identifier");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasComment("Invoice identifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Notes for the offer");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("datetime2")
                        .HasComment("Offer date");

                    b.Property<string>("OfferStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Offer status");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasComment("Request identifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("IX_Offer_DeliveryId");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_Offer_RequestId");

                    b.ToTable("Offers");

                    b.HasComment("Offer Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinalPrice = 4800m,
                            Notes = "Confirmed by client",
                            OfferDate = new DateTime(2024, 10, 18, 1, 10, 32, 353, DateTimeKind.Utc).AddTicks(1524),
                            OfferStatus = "Accepted",
                            RequestId = 1
                        });
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Request identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ApproximatePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Approximate price given by the company");

                    b.Property<decimal>("CalculatedPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Automatically calculated price");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Cargo type");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("int")
                        .HasComment("Client Company identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Date of creation");

                    b.Property<double>("DeliveryLatitude")
                        .HasColumnType("float")
                        .HasComment("Delivery address latitude");

                    b.Property<double>("DeliveryLongitude")
                        .HasColumnType("float")
                        .HasComment("Delivery address longitude");

                    b.Property<DateTime>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2")
                        .HasComment("Expected delivery date");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasComment("Height of the goods");

                    b.Property<bool>("IsRefrigerated")
                        .HasColumnType("bit")
                        .HasComment("Is the cargo refrigerated");

                    b.Property<int?>("Length")
                        .HasColumnType("int")
                        .HasComment("Length of the goods");

                    b.Property<int?>("NumberOfNonStandartGoods")
                        .HasColumnType("int")
                        .HasComment("Number of non-standart goods");

                    b.Property<int?>("NumberOfPallets")
                        .HasColumnType("int")
                        .HasComment("Number of pallets");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int")
                        .HasComment("Offer identifier");

                    b.Property<double?>("PalletHeight")
                        .HasColumnType("float")
                        .HasComment("Pallet height");

                    b.Property<double?>("PalletLength")
                        .HasColumnType("float")
                        .HasComment("Pallet length");

                    b.Property<double?>("PalletVolume")
                        .HasColumnType("float")
                        .HasComment("Pallet volume");

                    b.Property<double?>("PalletWidth")
                        .HasColumnType("float")
                        .HasComment("Pallet width");

                    b.Property<bool?>("PalletsAreStackable")
                        .HasColumnType("bit")
                        .HasComment("Are the pallets stackable");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("float")
                        .HasComment("Pickup address latitude");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("float")
                        .HasComment("Pickup address longitude");

                    b.Property<bool>("SharedTruck")
                        .HasColumnType("bit")
                        .HasComment("Will the vehicle be shared or no");

                    b.Property<string>("SpecialInstructions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Special instructions");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Status of the request");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Type of the request");

                    b.Property<string>("TypeOfGoods")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Type of goods");

                    b.Property<string>("TypeOfPallet")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Type of pallet");

                    b.Property<double?>("Volume")
                        .HasColumnType("float")
                        .HasComment("Volume of the goods");

                    b.Property<double?>("Weight")
                        .HasColumnType("float")
                        .HasComment("Weight of the goods");

                    b.Property<double?>("WeightOfPallets")
                        .HasColumnType("float")
                        .HasComment("Weight of pallets");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasComment("Width of the goods");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("Requests");

                    b.HasComment("Request Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApproximatePrice = 2000.00m,
                            CalculatedPrice = 2100.00m,
                            CargoType = "Standard",
                            ClientCompanyId = 1,
                            CreatedAt = new DateTime(2024, 10, 19, 4, 10, 33, 295, DateTimeKind.Local).AddTicks(5667),
                            DeliveryLatitude = 48.8566,
                            DeliveryLongitude = 2.3521999999999998,
                            ExpectedDeliveryDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRefrigerated = true,
                            NumberOfPallets = 10,
                            PalletHeight = 144.0,
                            PalletLength = 120.0,
                            PalletVolume = 1.3824000000000001,
                            PalletWidth = 80.0,
                            PalletsAreStackable = true,
                            PickupLatitude = 42.681199999999997,
                            PickupLongitude = 26.3187,
                            SharedTruck = false,
                            SpecialInstructions = "Handle with care",
                            Status = "Approved",
                            Type = "International",
                            TypeOfGoods = "Electronics",
                            TypeOfPallet = "Euro",
                            WeightOfPallets = 500.0
                        },
                        new
                        {
                            Id = 2,
                            ApproximatePrice = 1500.00m,
                            CalculatedPrice = 1550.00m,
                            CargoType = "Standard",
                            ClientCompanyId = 1,
                            CreatedAt = new DateTime(2024, 10, 19, 4, 10, 33, 295, DateTimeKind.Local).AddTicks(5803),
                            DeliveryLatitude = 42.697699999999998,
                            DeliveryLongitude = 23.321899999999999,
                            ExpectedDeliveryDate = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRefrigerated = true,
                            NumberOfPallets = 15,
                            PalletHeight = 160.0,
                            PalletLength = 120.0,
                            PalletVolume = 1.536,
                            PalletWidth = 80.0,
                            PalletsAreStackable = true,
                            PickupLatitude = 42.681199999999997,
                            PickupLongitude = 26.3187,
                            SharedTruck = false,
                            SpecialInstructions = "Keep refrigerated",
                            Status = "pending",
                            Type = "Domestic",
                            TypeOfGoods = "Food Products",
                            TypeOfPallet = "Euro",
                            WeightOfPallets = 750.0
                        },
                        new
                        {
                            Id = 3,
                            ApproximatePrice = 1800.00m,
                            CalculatedPrice = 1850.00m,
                            CargoType = "Standard",
                            ClientCompanyId = 1,
                            CreatedAt = new DateTime(2024, 10, 19, 4, 10, 33, 295, DateTimeKind.Local).AddTicks(5812),
                            DeliveryLatitude = 48.208199999999998,
                            DeliveryLongitude = 16.373799999999999,
                            ExpectedDeliveryDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRefrigerated = false,
                            NumberOfPallets = 8,
                            PalletHeight = 150.0,
                            PalletLength = 120.0,
                            PalletVolume = 1.8,
                            PalletWidth = 100.0,
                            PalletsAreStackable = false,
                            PickupLatitude = 42.681199999999997,
                            PickupLongitude = 26.3187,
                            SharedTruck = true,
                            SpecialInstructions = "Use soft padding",
                            Status = "Pending",
                            Type = "International",
                            TypeOfGoods = "Furniture",
                            TypeOfPallet = "Industrial",
                            WeightOfPallets = 400.0
                        },
                        new
                        {
                            Id = 4,
                            ApproximatePrice = 1700.00m,
                            CalculatedPrice = 1750.00m,
                            CargoType = "Standard",
                            ClientCompanyId = 1,
                            CreatedAt = new DateTime(2024, 10, 19, 4, 10, 33, 295, DateTimeKind.Local).AddTicks(5820),
                            DeliveryLatitude = 43.835599999999999,
                            DeliveryLongitude = 25.965699999999998,
                            ExpectedDeliveryDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRefrigerated = false,
                            NumberOfPallets = 12,
                            PalletHeight = 130.0,
                            PalletLength = 120.0,
                            PalletVolume = 1.5600000000000001,
                            PalletWidth = 100.0,
                            PalletsAreStackable = true,
                            PickupLatitude = 42.681199999999997,
                            PickupLongitude = 26.3187,
                            SharedTruck = true,
                            SpecialInstructions = "Avoid moisture",
                            Status = "Pending",
                            Type = "Domestic",
                            TypeOfGoods = "Machinery Parts",
                            TypeOfPallet = "Industrial",
                            WeightOfPallets = 600.0
                        });
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Vehicle identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ArePalletsStackable")
                        .HasColumnType("bit")
                        .HasComment("Are the pallets stackable");

                    b.Property<int?>("EuroPalletCapacity")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasComment("Euro pallets capacity");

                    b.Property<double>("FuelConsumptionPer100Km")
                        .HasColumnType("float")
                        .HasComment("Fuel consumption per 100 km");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasComment("Vehicle height");

                    b.Property<int?>("IndustrialPalletCapacity")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasComment("Industrial pallets capacity");

                    b.Property<double>("Length")
                        .HasColumnType("float")
                        .HasComment("Vehicle length");

                    b.Property<DateTime?>("MaintenanceDue")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasComment("Maintenance due date");

                    b.Property<double>("MaxWeightCapacity")
                        .HasColumnType("float")
                        .HasComment("Max weight capacity");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasComment("Vehicle registration number");

                    b.Property<string>("VehicleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Vehicle status");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Vehicle type");

                    b.Property<double>("Volume")
                        .HasColumnType("float")
                        .HasComment("Vehicle volume");

                    b.Property<double>("Width")
                        .HasColumnType("float")
                        .HasComment("Vehicle width");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasComment("Vehicle Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArePalletsStackable = true,
                            EuroPalletCapacity = 10,
                            FuelConsumptionPer100Km = 28.5,
                            Height = 2.6000000000000001,
                            IndustrialPalletCapacity = 8,
                            Length = 7.5,
                            MaintenanceDue = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxWeightCapacity = 10000.0,
                            RegistrationNumber = "BG1234RE",
                            VehicleStatus = "Not Available",
                            VehicleType = "Refrigerated Truck",
                            Volume = 48.75,
                            Width = 2.5
                        },
                        new
                        {
                            Id = 2,
                            ArePalletsStackable = true,
                            EuroPalletCapacity = 33,
                            FuelConsumptionPer100Km = 32.0,
                            Height = 2.7000000000000002,
                            IndustrialPalletCapacity = 26,
                            Length = 13.6,
                            MaintenanceDue = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxWeightCapacity = 24000.0,
                            RegistrationNumber = "BG5678TT",
                            VehicleStatus = "Available",
                            VehicleType = "Tent Truck",
                            Volume = 91.799999999999997,
                            Width = 2.5
                        });
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Cash Register identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Amount of the register");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2")
                        .HasComment("Date submitted");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Description of the register");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Type of the register");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.ToTable("CashRegisters");

                    b.HasComment("Cash Register Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 200m,
                            DateSubmitted = new DateTime(2024, 10, 19, 1, 10, 32, 327, DateTimeKind.Utc).AddTicks(6324),
                            DeliveryId = 1,
                            Description = "Fuel cost",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50m,
                            DateSubmitted = new DateTime(2024, 10, 19, 1, 10, 32, 327, DateTimeKind.Utc).AddTicks(6325),
                            DeliveryId = 1,
                            Description = "Toll fee",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasComment("Driver identifier");

                    b.Property<int>("OfferId")
                        .HasColumnType("int")
                        .HasComment("Offer identifier");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Delivery total income");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Delivery reference number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Delivery status");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Delivery total expenses");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasComment("Vehicle identifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("IX_Delivery_DriverId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_Delivery_VehicleId");

                    b.ToTable("Deliveries");

                    b.HasComment("Delivery Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 1,
                            OfferId = 1,
                            Profit = 4300m,
                            ReferenceNumber = "REF-2024-0001",
                            Status = "In Progress",
                            TotalExpenses = 500m,
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.DeliveryTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasComment("Delivery identifier");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasComment("Driver identifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasComment("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasComment("Longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Notes");

                    b.Property<string>("StatusUpdate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Status update");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasComment("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("DriverId");

                    b.ToTable("DeliveryTrackings");

                    b.HasComment("Delivery Tracking Entity");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Driver identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Driver's age");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasComment("Is driver available");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2")
                        .HasComment("Driver's license expiry date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Driver's license number");

                    b.Property<int>("MonthsOfExperience")
                        .HasColumnType("int")
                        .HasComment("Driver's months of experience");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Driver's name");

                    b.Property<string>("Preferrences")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Driver's preferrences");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Driver's salary");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int")
                        .HasComment("Driver's year of experience");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drivers");

                    b.HasComment("Driver Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            IsAvailable = false,
                            LicenseExpiryDate = new DateTime(2026, 10, 19, 1, 10, 32, 342, DateTimeKind.Utc).AddTicks(7910),
                            LicenseNumber = "DL123456",
                            MonthsOfExperience = 6,
                            Name = "Paul Smith",
                            Preferrences = "Long-distance deliveries",
                            Salary = 3000m,
                            UserId = "2e8be95a-186e-403b-b4aa-3874750a3563",
                            YearOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            IsAvailable = true,
                            LicenseExpiryDate = new DateTime(2027, 10, 19, 1, 10, 32, 342, DateTimeKind.Utc).AddTicks(7913),
                            LicenseNumber = "DL654321",
                            MonthsOfExperience = 4,
                            Name = "Mark Driver",
                            Preferrences = "Short-distance deliveries",
                            Salary = 2800m,
                            UserId = "38ba6810-2800-4ac8-b005-5c27e8248951",
                            YearOfExperience = 8
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99027aaa-d346-4dd9-a467-15d74576c080",
                            ConcurrencyStamp = "e3ef4f83-ca6e-460a-bad7-f95b41acf3e2",
                            Name = "LogisticsCompany",
                            NormalizedName = "LOGISTICSCOMPANY"
                        },
                        new
                        {
                            Id = "5d000e64-c056-419a-950f-1992bd1e910d",
                            ConcurrencyStamp = "398093c2-15a8-4282-94a8-8c93269131ac",
                            Name = "ClientCompany",
                            NormalizedName = "CLIENTCOMPANY"
                        },
                        new
                        {
                            Id = "20ddc22c-ca6d-4feb-a688-0f31a430b5eb",
                            ConcurrencyStamp = "4b69ec24-4dc8-4cb0-97bf-c912c4a627c8",
                            Name = "Secretary",
                            NormalizedName = "SECRETARY"
                        },
                        new
                        {
                            Id = "27609f35-fbc8-4dc4-9d12-7ff2dd400327",
                            ConcurrencyStamp = "2f6eb017-ef3e-4b1c-ab49-8cbb8d59af86",
                            Name = "Speditor",
                            NormalizedName = "SPEDITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6bab54d5-5a88-4128-92d2-4d12ad0baa32",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5abdcb8d-5885-4013-be05-394c82ef2b2a",
                            Email = "logistics@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEEE01UKz3R8FfZLMhrpqP70r5h81XnQnoa1CrfTJjJ9DKtcByqWj1FFSA4E5KtLEOQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "952f2971-deb2-4dd4-a30d-4c5c86905273",
                            TwoFactorEnabled = false,
                            UserName = "logistics"
                        },
                        new
                        {
                            Id = "20450cff-816f-49c8-9546-1c603aec0301",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ed4eb45-1fba-477b-a84c-e097f6542222",
                            Email = "clientcompany1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEIeWgS4FRlGaJIktGDbvoqT/5UxY37NVFTssJ6oLLq3QfoJOckar81bWYrgmeiBGhA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a096abd8-f984-4d3c-9e7f-ef7a981e3b46",
                            TwoFactorEnabled = false,
                            UserName = "clientcompany1"
                        },
                        new
                        {
                            Id = "38ba6810-2800-4ac8-b005-5c27e8248951",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46b006dd-bf9a-47b8-9d0d-e792a817b632",
                            Email = "secretary@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEK6jwLAml+Iza+HzShXoQB+WAKcg6P6z6now1OAVjeZHvxqIqSIDxcw9MjaM7ygZIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "63e5106b-9e72-48a2-ab1b-c2ea175634ee",
                            TwoFactorEnabled = false,
                            UserName = "secretary"
                        },
                        new
                        {
                            Id = "2e8be95a-186e-403b-b4aa-3874750a3563",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c95e9cc0-9cc2-4470-991b-47bd4efe9942",
                            Email = "speditor@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEAUcl63CFFvvMCLIUL0s+i1Y1tGpC1r8OhQLUxKrCK+i/ZdOKaNxDRd0QgIZxQ2krg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96b72427-6121-4c08-90b0-527624d3d86b",
                            TwoFactorEnabled = false,
                            UserName = "speditor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "6bab54d5-5a88-4128-92d2-4d12ad0baa32",
                            RoleId = "99027aaa-d346-4dd9-a467-15d74576c080"
                        },
                        new
                        {
                            UserId = "20450cff-816f-49c8-9546-1c603aec0301",
                            RoleId = "5d000e64-c056-419a-950f-1992bd1e910d"
                        },
                        new
                        {
                            UserId = "38ba6810-2800-4ac8-b005-5c27e8248951",
                            RoleId = "20ddc22c-ca6d-4feb-a688-0f31a430b5eb"
                        },
                        new
                        {
                            UserId = "2e8be95a-186e-403b-b4aa-3874750a3563",
                            RoleId = "27609f35-fbc8-4dc4-9d12-7ff2dd400327"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Invoice", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", null)
                        .WithMany("Invoices")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Offer", "Offer")
                        .WithOne("Invoice")
                        .HasForeignKey("LogisticsSystem.Infrastructure.Data.DataModels.Invoice", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Offer", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", null)
                        .WithMany("Offers")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Request", "Request")
                        .WithOne("Offer")
                        .HasForeignKey("LogisticsSystem.Infrastructure.Data.DataModels.Offer", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Request", b =>
                {
                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", "ClientCompany")
                        .WithMany("Requests")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.CashRegister", b =>
                {
                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Delivery", "Delivery")
                        .WithMany("CashRegisters")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Delivery", b =>
                {
                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Driver", "Driver")
                        .WithMany("Deliveries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Offer", "Offer")
                        .WithOne("Delivery")
                        .HasForeignKey("LogiTrack.Infrastructure.Data.DataModels.Delivery", "OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticsSystem.Infrastructure.Data.DataModels.Vehicle", "Vehicle")
                        .WithMany("Deliveries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Offer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.DeliveryTracking", b =>
                {
                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Delivery", "Delivery")
                        .WithMany("DeliveryTrackings")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiTrack.Infrastructure.Data.DataModels.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Driver", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("LogiTrack.Infrastructure.Data.DataModels.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.ClientCompany", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Offers");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Offer", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Request", b =>
                {
                    b.Navigation("Offer");
                });

            modelBuilder.Entity("LogisticsSystem.Infrastructure.Data.DataModels.Vehicle", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Delivery", b =>
                {
                    b.Navigation("CashRegisters");

                    b.Navigation("DeliveryTrackings");
                });

            modelBuilder.Entity("LogiTrack.Infrastructure.Data.DataModels.Driver", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
